<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>Wandur</AssemblyName>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <ApplicationIcon>Assets/Wandur.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <AvaloniaResource Include="Assets/icon-256.png" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Wandur.Core/Wandur.Core.csproj" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
    <PackageReference Include="Iciclecreek.Avalonia.Terminal" Version="4.0.2" />
    <PackageReference Include="Avalonia.AvaloniaEdit" Version="12.0.0" />
    <PackageReference Include="Avalonia.Controls.ColorPicker" Version="12.1.2" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.2" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.2" />
    <PackageReference Include="Dock.Avalonia" Version="12.1.0.6" />
    <PackageReference Include="Dock.Model.Mvvm" Version="12.1.0.6" />
    <PackageReference Include="Dock.Avalonia.Themes.Fluent" Version="12.1.0.6" />
  </ItemGroup>
</Project>
