#!/usr/bin/env python3
"""Regenerate the strongly typed .resx facade; --check detects drift in CI."""
from pathlib import Path
import argparse
import xml.etree.ElementTree as ET

parser = argparse.ArgumentParser()
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
folder = Path(__file__).resolve().parents[1] / 'src/Wandur.Core/Localization'
keys = [entry.attrib['name'] for entry in ET.parse(folder / 'Strings.resx').findall('data')]
if len(set(key.casefold() for key in keys)) != len(keys):
    raise SystemExit('Resource keys must be unique ignoring case.')
text = '''// Generated by scripts/generate-localization.py. Edit Strings.resx, then regenerate.
using System.Globalization;
using System.Resources;

namespace Wandur.Core.Localization;

public static class Strings
{
    public static ResourceManager ResourceManager { get; } = new("Wandur.Core.Localization.Strings", typeof(Strings).Assembly);
    private static string Get(string key) => ResourceManager.GetString(key, UiLanguage.Culture) ?? throw new MissingManifestResourceException(key);
    public static string Format(string value, params object?[] args) => string.Format(UiLanguage.Culture, value, args);
'''
text += ''.join(f'    public static string {key} => Get(nameof({key}));\n' for key in keys) + '}\n'
output = folder / 'Strings.cs'
if args.check:
    if output.read_text() != text:
        raise SystemExit('Strings.cs is out of date. Run python3 scripts/generate-localization.py.')
else:
    output.write_text(text)
